name: Pull request.

env:
  FORCE_COLOR: '1'
on:
  pull_request:
    branches: [ main ]

jobs:
# --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
  development:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: E2E Tests
        run: npm run test:int

      - name: Build documentation.
        env:
          BASE_URL: '/pw-codeceptjs/'
        run: npm run docs:build

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-results
          path: playwright-report
